export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";


export const PRODUCT_DETAILS_REQUEST = "PRODUCT-DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_SEARCH_REQUEST = "PRODUCT_SEARCH_REQUEST";
export const PRODUCT_SEARCH_SUCCESS = "PRODUCT_SEARCH_SUCCESS";
export const PRODUCT_SEARCH_FAIL = "PRODUCT_SEARCH_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";

export const PRODUCT_RECOMANDATION_REQUEST = "PRODUCT_RECOMANDATION_REQUEST";
export const PRODUCT_RECOMANDATION_SUCCESS = "PRODUCT_RECOMANDATION_SUCCESS";
export const PRODUCT_RECOMANDATION_FAIL = "PRODUCT_RECOMANDATION_FAIL";

export const CART_RECOMANDATION_SYSTEM_REQUEST="CART_RECOMANDATION_SYSTEM_REQUEST";
export const CART_RECOMANDATION_SYSTEM_SUCCESS="CART_RECOMANDATION_SYSTEM_SUCCESS";
export const CART_RECOMANDATION_SYSTEM_FAIL="CART_RECOMANDATION_SYSTEM_FAIL";

export const PRODUCT_UPDATE_REQUEST="PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS="PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL="PRODUCT_UPDATE_FAIL";

export const ALL_REVIEWS_REQUEST="ALL_REVIEWS_REQUEST";
export const ALL_REVIEWS_SUCCESS="ALL_REVIEWS_SUCCESS";
export const ALL_REVIEWS_FAIL="ALL_REVIEWS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
